name: Build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: maven
          server-id: 'github'
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        run: |
          ./mvnw ${MAVEN_CLI_OPTS} install
#      - name: Test with Maven
#        run: |
#          unset GITHUB_ACTIONS
#          ./mvnw ${MAVEN_CLI_OPTS} failsafe:integration-test failsafe:verify
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy ${MAVEN_CLI_OPTS} -DskipTests -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
